### ISSUE TITLE
-PROBLEM Configuration: Setup a list of methods accepted for a certain route (e.g., try to delete something with and without permission).

### ISSUE THREAD

**Issue by MaxIhme** [RanniSch/Webserv#37]

**Comment by MaxIhme** [comment]
-PROBLEM
Server hangs forever (file exists)
with postman  127.0.0.1:8000/delete_dir/delete_me.txt

config:

	location /delete_dir
	{
		allow_methods DELETE;
	}

also hangs when

config:

	location /delete_dir
	{
		#allow_methods DELETE;
	}

**Comment by RanniSch** [comment]
@MaxIhme server does not hang, but the delete_me.txt gets downloaded instead of deleted.

I tested: http://localhost:8000/delete_dir/delete_me.txt

**Comment by LukasKava** [comment]
DELETION WORKS FOR ME  server doesnt hang and it responds properly. Tested with:  curl -X DELETE 127.0.0.1:8000/delete_dir/delete_me.txt

**Comment by LukasKava** [comment]
> @MaxIhme server does not hang, but the delete_me.txt gets downloaded instead of deleted.
> 
> I tested: http://localhost:8000/delete_dir/delete_me.txt

Ranja It is working how its intended if you just do this link to the browser it send the GET request to get the delete_me.txt you have to either make DELETE request with the curl or the postman

**Comment by LukasKava** [comment]
I tested deleting the file that is outside delete_dir it did not work I commented out allowed methods DELETE it was still okay because the server allows the method delete on its own

**Comment by RanniSch** [comment]
close
