### ISSUE TITLE
Configuration: Setup routes in a server to different directories.

### ISSUE THREAD

**Issue by MaxIhme** [RanniSch/Webserv#40]
the function seems all good, but the server has problems.

config:
	location /
	{
		index index.html;
		allowed_Methods POST;
	}

	location /delete_dir
	{
		allow_methods DELETE;
	}

	location /static_website
	{
		allow_methods GET;
		index static.html;
	}

http://localhost:8000/ -> error page 405 method not allowed -> correct

but Segfault:
"Listening Socket onject for Port: 8090fd: 5 succesfully created!
ERROR: poll() has timed out: : No such file or directory
ACCEPT CONNECTION => 3DONE

READING AND PARSING! [NOTHING]
TMP_METHOD: [GET]
CHOSEN METHOD: [GET]
PREPARING RESPONSE 1
PREPARING RESPONSE 2
CRAFTED GET RESPONSE STR
ACCEPT CONNECTION => 3DONE

WE HAVE FINISHED WRITING TO THE BROWSER
Client Socket: 6 was closed successfuly
File deleted successfully: tmp/tmp_file_6
make: *** [e] Segmentation fault: 11
mbp:simplified-serv maxrehberg$ "

restart try again, same segfault. restart try again, same segfault. 

try: http://localhost:8000/static_website/
page loaded, pictures not, same segfault
restart try again, same segfault.

restart try again, all good, i can reload the page.
restart, browser hangs. debugging says it hangs at "int		TestServer::checkPollAction(short revents, int fd)" second if (like in the screenshot).

**Comment by RanniSch** [comment]
I do not get a seg fault, when "http://localhost:8000/" but is automatically goes to "http://localhost:8000/index.html" which is set in the config file.

http://localhost:8000/static_website/ no seg fault for me

**Comment by LukasKava** [comment]
No seg fault for me either @MaxIhme please do a retest

**Comment by RanniSch** [comment]
Works fine
