### ISSUE TITLE
PROBLEM check https://localhost:8000

### ISSUE THREAD

**Issue by MaxIhme** [RanniSch/Webserv#43]
@LukasKava 
https://localhost:8000 results in a full terminal of 
FILE WAS NOT BEEN OPEN!
because:
socket.setResponseFile(filename) is not set
because it does not go to
TestServer::_saveResponseToAFile

**Comment by MaxIhme** [comment]
also check https://localhost and ftp:// and http:/local und so

**Comment by MaxIhme** [comment]
TestServer::_readAndParseHeader returns -1
because 
TestServer::_checkForMethods cannot find a method
because 
strBuffer is shitty
![Bildschirmfoto 2023-10-28 um 11 49 42](https://github.com/RanniSch/Webserv/assets/79764057/e7b207e4-7ef1-4f43-827b-f74e8526c6a0)

**Comment by LukasKava** [comment]
Tested seems that It is okay now and does not result in FILE WAS NOT BEEN open also no crash or hangs @MaxIhme

**Comment by RanniSch** [comment]
For me it gives:
![image](https://github.com/RanniSch/Webserv/assets/104382315/a24dcc0b-35fc-4153-abcf-ac4f04c94885)

**Comment by RanniSch** [comment]
ok
