### ISSUE TITLE
Check CGI: The CGI should be run in the correct directory for relative path file access.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#45]
I could open two different Scripts. Tested with: localhost:8000/cgi-bin/script-get-2.py and with localhost:8000/cgi-bin/script-post-2.py

**Comment by MaxIhme** [comment]
http://localhost:8000/cgi-bin/first_cgi.py with a 
define CGI_TIMEOUT		1000
results in 508 - Loop detected
with 
define CGI_TIMEOUT		10000
downloads the python script and 
make: *** [e] Segmentation fault: 11

localhost:8000/cgi-bin/script-get-2.py the same


Ranja: For me both scripts download without error or segfault. I just wonder why I don't see the result in the browser anymore.
@MaxIhme @LukasKava

**Comment by LukasKava** [comment]
TESTED with all scripts and TImeouts it works well and no dowloading of the Files seems like new version fixes it @MaxIhme  @RanniSch  retest it please

**Comment by RanniSch** [comment]
Works fine now
