### ISSUE TITLE
Check CGI: With the help of the students you should check that everything is working properly. You have to test the CGI with the "GET" and "POST" methods.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#46]
Tested with:
http://localhost:8000/cgi-bin/script-get-2.py
and with
http://localhost:8000/index.html

Why is the script for "http://localhost:8000/cgi-bin/script-get-2.py" downloaded and not anymore on the browser screen? @MaxIhme @LukasKava

**Comment by MaxIhme** [comment]
works via docker

**Comment by LukasKava** [comment]
SEEMS TO work well and no issues anymore

**Comment by RanniSch** [comment]
Works fine now
