### ISSUE TITLE
Check with a browser: Use the reference browser of the team. Open the network part of it, and try to connect to the server using it.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#47]
Connected with:
http://localhost:8000/animal.jpg
http://localhost:8000/upload.html --> file saved in www
http://localhost:8000/index.html
localhost:8000/cgi-bin/script-get-2.py

**Comment by MaxIhme** [comment]
Google Chrome -> Anzeigen -> Entwickler -> Entwicklertools
shows for http://localhost:8000/index.html 200 status and for facicon also

**Comment by LukasKava** [comment]
Tested the cases and http://localhost:8000/cgi-bin/script-infinite-loop.py looks to work fine

**Comment by RanniSch** [comment]
All works fine.
