### ISSUE TITLE
PROBLEM: Basic checks: Using telnet, curl, prepared files, demonstrate that the following features work properly: Upload some file to the server and get it back.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#58]
Tested with: http://localhost:8000/upload.html

Uploaded a jpg, png, gif, pdf, mp4 and prproj

Mp4 and prproj is returned as a download.

The PDF Subject gets printed on the screen, Terminal produces errors. Or is meant with error:0 that there is no error? Similar output with socket 11 for the mp4 data type.  Max: I think it means that the error is 0, so nothing
![image](https://github.com/RanniSch/Webserv/assets/104382315/de9b4d4f-b61e-4f02-b11d-afe2e25cc4b0)

**Comment by MaxIhme** [comment]
tryed to upload a zip -> payload to large (43 MB , correct )

PROBLEM zip uploaded with emptyspaces does not work -> @MaxIhme 
http://localhost:8000/Bildschirmfoto%202023-10-31%20um%2013.52.58.zip

again with a zip 
returns http://localhost:8000/127.0.0.1:8000 
http://localhost:8000/Bildschirmfot.zip is downloadable -> correct

uploaded Bildsch.png
http://localhost:8000/Bildsch.png -> can view in the browser

upload of pdf good
http://localhost:8000/Epson_02022023085138 -> downloaded (correct)

subject.pdf upload was successfull
http://localhost:8000/en.subject(22).pdf -> was downloaded (correct)

upload of jpg successfull
http://localhost:8000/little-max.jpg -> was shown (correct)

txt upload successfull
http://localhost:8000/rSyncErrors.txt -> was downloaded (correct) -> for me ok that it will not be shown (no explicite naming in subject)

**Comment by RanniSch** [comment]
wokrs
