### ISSUE TITLE
PROBLEM: Basic checks: Using telnet, curl, prepared files, demonstrate that the following features work properly: GET, POST and DELETE requests should work.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#59]
Tested GET and POST successfully (with http://localhost:8000/upload.html; without and with config file), but not DELETE.

**Comment by MaxIhme** [comment]
PROBLEM
DELETE to http://localhost:8000 hangs in Docker and on mac

@LukasKava there is no DELETE case in TestServer?
to execute a delte and get a response message create ResponseMessage rm(<request>) (and give it the request) and then do rm.createResponse() then it deletes the file (if allowed) and gives you back an apropriate message.
![Bildschirmfoto 2023-10-31 um 13 52 58](https://github.com/RanniSch/Webserv/assets/79764057/1d4686f1-e1e3-4c38-9447-b3f171c2cd0f)

**Comment by RanniSch** [comment]
ok
