### ISSUE TITLE
PROBLEM Check with a browser: It should be compatible to serve a fully static website.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#61]
http://localhost:8000/animal.jpg worked fine.

**Comment by MaxIhme** [comment]
PROBLEM
static website:
http://localhost:8010/static_website
gives 
http://localhost:8010/static_website/static.html -> works fine

but clicking on the link gives:
http://localhost:8010/index.html not 
http://localhost:8010/static_website/index.html -> @MaxIhme

**Comment by RanniSch** [comment]
these three work for me:
http://localhost:8010/static_website
http://localhost:8010/static_website/static.html 
http://localhost:8010/index.html

**Comment by RanniSch** [comment]
I have the same problems

**Comment by RanniSch** [comment]
it is ok
