### ISSUE TITLE
Check with a browser: Look at the request header and response header.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#62]
Tested with Web Developer mode in Mozilla Firefox for:
http://localhost:8000/animal.jpg
http://localhost:8000/upload.html
http://localhost:8000/index.html and sending "Hi" and "Hiii"

**Comment by MaxIhme** [comment]
https://localhost:8000 -> browser says "localhost hat eine ungültige Antwort gesendet."
server: [ERROR]: Exception: ERROR: Not Implemented 501
[ERROR]: Writing error.

-> for me ok

**Comment by MaxIhme** [comment]
all in Firefox Developer mode:
http://localhost:8000/

HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Content-Length: 250


Firefox wants to have
http://localhost:8000/favicon.ico
results in 
HTTP/1.1 404 Not Found
Content-type: text/html; charset=UTF-8
Content-Length: 316

but when I type 
http://localhost:8000/favicon.ico
it downloads the icon      -> not pretty but ok for me 
update: also works fine, the browser can load it

**Comment by MaxIhme** [comment]
http://localhost:8000/static_website with one html and 2 pictures

HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Content-Length: 401

HTTP/1.1 200 OK
Content-Type: image/jpg
Content-Length: 230314

HTTP/1.1 200 OK
Content-Type: image/jpg
Content-Length: 101563

for favicon: -> gives it as binary, not as picture -> I would say leave it
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Content-Length: 15406

**Comment by MaxIhme** [comment]
http://localhost:8000/dir_listing

HTTP/1.1 301 Moved Permanently
Location: localhost:8000/dir_listing/
Content-Type: text/html; charset=UTF-8
Content-Length: 720

Firefox says:
"Adresse nicht erkannt

Firefox weiß nicht, wie diese Adresse geöffnet werden soll, da eines der folgenden (http) kein registriertes Protokoll oder in diesem Kontext nicht erlaubt ist."

you first have to go to 
localhost:8000/dir_listing/
and then you can do 
localhost:8000/dir_listing
and it redirects to 
localhost:8000/dir_listing/
-> I would say leave it

**Comment by RanniSch** [comment]
Fine for me
