### ISSUE TITLE
PROBLEM Check with a browser: Try anything you want to.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#63]
Went through all our .html files in "www" folder (without the config file).

**Comment by MaxIhme** [comment]
PROBLEM
http://localhost:8010/dir_li -> 404
and then 
http://localhost:8010/dir_li -> does not work -> @MaxIhme 
but that works again:
http://localhost:8010/dir_listing/

http://localhost:8010/static_website works

PROBLEM then click on link and comes:
http://localhost:8010/index.html 
not 
http://localhost:8010/static_website/index.html as supposed

http://localhost:8000/cgi-bin/script-post-2.py does not work on Mac as I know already

**Comment by MaxIhme** [comment]
https://localhost:8000/ -> browser says "localhost hat eine ungültige Antwort gesendet."
server: [ERROR]: Exception: ERROR: Not Implemented 501
[ERROR]: Writing error.

-> for me ok

**Comment by RanniSch** [comment]
it is ok
