### ISSUE TITLE
PROBLEM: Port issues: In the configuration file setup multiple ports and use different websites. Use the browser to ensure that the configuration works as expected and shows the right website.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#64]
Tested with "default.conf"

and using
http://localhost:8000/upload.html
http://localhost:8080/index.html
http://localhost:8010/cgi-bin/script-get-2.py?a=w

**Comment by MaxIhme** [comment]
config:
server
{
    listen 8000 8080 8010;
...
}

http://localhost:8000/    works
http://localhost:8010/dir_listing/   works
http://localhost:8080/static_website   works

**Comment by RanniSch** [comment]
@MaxIhme @LukasKava It seg faults. Ports 8000, 8010, 8080 with ./webserv default.conf

in 30% it works, the rest of the time server starts segg faulting while opening the third port
![image](https://github.com/RanniSch/Webserv/assets/104382315/24ff6041-168c-43a8-b62d-c12ce5991f73)

**Comment by MaxIhme** [comment]
@LukasKava that is what we had as we were coding together. To handle that you had to copy everything from socket I think. 

Hmm, on Docker I get the segfault and for debugging on Mac not :(
<img width="745" alt="Bildschirmfoto 2023-11-01 um 19 33 06" src="https://github.com/RanniSch/Webserv/assets/79764057/ac088392-9c0c-49fa-89f6-9e3fe0353466">

**Comment by RanniSch** [comment]
All tests work fine
