### ISSUE TITLE
Port issues: In the configuration, try to setup the same port multiple times. It should not work.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#65]
Testresult after opening 3 times port 8000 in the default.config file:

./webserv default.conf

Information: cannot open your config file. Will take default Config.
TestServer constructor called!
Start Listening...
Start Listening...
bind failed... : Address already in use

**Comment by MaxIhme** [comment]
config:
server
{
    listen 8000 8080 8000;
...
}

./webserv conf/webserve.conf
TestServer constructor called!
Start Listening...
Error: Binding failed
make: *** [e] Error 1

**Comment by RanniSch** [comment]
I also ran @MaxIhme example with valgrind and I get again the same amount of reachable memory (no control + c needed)
![image](https://github.com/RanniSch/Webserv/assets/104382315/37e9c73c-f120-4ebe-8f15-48e8c0b09009)

without valgrind same result:
./webserv default.conf
Information: cannot open your config file. Will take default Config.
TestServer constructor called!
Start Listening...
Start Listening...
Start Listening...
Error: Binding failed

**Comment by RanniSch** [comment]
I would say, that's fine
![image](https://github.com/RanniSch/Webserv/assets/104382315/1198babc-7aaa-4727-931a-cd486a28a8e6)
