### ISSUE TITLE
PROBLEM: Siege & stress test: Use Siege to run some stress tests.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#68]
siege -c 10 -t 1M http://localhost:8000/animal.jpg  --> unsure if I should call this a good or a fail. Siege has no failed transactions. Webserver shows error
![image](https://github.com/RanniSch/Webserv/assets/104382315/352724ec-9089-4fa0-bd78-b5925724c6cb)

siege -c 10 -t 1M http://localhost:8000/upload.html --> successfull
![image](https://github.com/RanniSch/Webserv/assets/104382315/a523f691-625f-4448-8626-fa99d4032df3)

siege -c 10 -t 1M http://localhost:8000/index.html --> successfull
![image](https://github.com/RanniSch/Webserv/assets/104382315/36e18077-9e35-4bea-b31d-7318da94dbbe)

siege -c 10 -t 1M http://localhost:8000/cgi-bin/script-post-2.py --> successfull
![image](https://github.com/RanniSch/Webserv/assets/104382315/bb29428a-c5c0-4893-b00f-0cbd0b1215f3)

**Comment by MaxIhme** [comment]
on Mac:
siege -c 10 -t 1M http://localhost:8000/animal.jpg
<img width="575" alt="Bildschirmfoto 2023-10-31 um 19 26 10" src="https://github.com/RanniSch/Webserv/assets/79764057/fef8dc82-e153-460c-b6ba-e2bc316673f4">

without restarting: 
siege -c 10 -t 1M http://localhost:8000/upload.html 
<img width="607" alt="Bildschirmfoto 2023-10-31 um 19 27 52" src="https://github.com/RanniSch/Webserv/assets/79764057/f8c93455-0b48-435d-af76-bde79b62f7a7">

without restarting:
siege -c 10 -t 1M http://localhost:8000/index.html 
<img width="573" alt="Bildschirmfoto 2023-10-31 um 19 29 32" src="https://github.com/RanniSch/Webserv/assets/79764057/d9b49f95-7ef1-4d0c-9b91-b237dc1cfaef">

siege -c 10 -t 1M http://localhost:8000/cgi-bin/script-post-2.py --> cgi does not work on my mac

**Comment by RanniSch** [comment]
That looks promising, let's see what @LukasKava gets.

**Comment by RanniSch** [comment]
All test work fine
