### ISSUE TITLE
Siege & stress test: Availability should be above 99.5% for a simple GET on an empty page with a siege -b on that page.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#69]
Retested with: siege -b http://localhost:8000/email.html
What do they mean by "simple GET on an empty page"? Maybe we should make the html more simple?

siege -b http://localhost:8000/listing_Kopie.html  --> Failed transactions shown by siege, but Server did not crash and availability over 99.5%
![image](https://github.com/RanniSch/Webserv/assets/104382315/e3e64994-7596-4e8a-a195-f61302673a64)

![image](https://github.com/RanniSch/Webserv/assets/104382315/9cc31780-d4b1-4579-8408-d9163cf500b8)

**Comment by MaxIhme** [comment]
summary: segfaults and stuff on mac -> let's count on Lucas linux results

on Mac:
siege -b http://localhost:8000/listing_Kopie.html 
<img width="619" alt="Bildschirmfoto 2023-10-31 um 19 05 52" src="https://github.com/RanniSch/Webserv/assets/79764057/4cc233cc-ca37-4b2b-a03e-532a5b2dec4f">

and try again -> segfault and Bad Access 
after some recompilation and restarts I tried:
http://localhost:8000/index.html 
<img width="620" alt="Bildschirmfoto 2023-10-31 um 19 15 50" src="https://github.com/RanniSch/Webserv/assets/79764057/a919a218-f40a-406a-b9ac-66716c36ba9d">

**Comment by RanniSch** [comment]
Ok, @LukasKava let's see what you get.

**Comment by MaxIhme** [comment]
via Docker
siege -b http://localhost:8000/email.html -> 99,79% available
siege -b http://localhost:8000/listing_Kopie.html  -> 99,9%
siege -b http://localhost:8000/listing_Kopie.ht  -> 99,59%

-> ok for me

**Comment by RanniSch** [comment]
fine
