### ISSUE TITLE
Configuration: • Limit the client body (use: curl -X POST -H "Content-Type: plain/text" --data "BODY IS HERE write something shorter or longer than body limit").

### ISSUE THREAD

**Issue by MaxIhme** [RanniSch/Webserv#74]
config:

server
{
...
	max_body_size 1;
....
}
normally when we go to: http://localhost:8000/ and klick on "send" it should be a bigger body then 1Byte (say=Hi). But it does not say that the client body is too big. I tried it via docker and there it executed the script normally. I think Lukas is still on implementing that.

**Comment by RanniSch** [comment]
at MaxIhme How did you test this?

EDIT Max: I didconfig:
...
	max_body_size 50000;
...

and uploaded a picture with 67 kB (67000) -> did not work

and then config:
...
	max_body_size 80000;
...
same picture -> did work  -> for me ok

**Comment by RanniSch** [comment]
fine
